controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
catch_all:
  path: "/{url}"
  controller: App\Controller\NewController::index
  requirements:
    url: .*
